[tool.poetry]
name = "task3-1"
version = "0.1.0"
description = ""
authors = ["Muharbi <you@example.com>"]
readme = "README.md"
packages = [{include = "task3"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
